channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=24.3.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==6.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
